#!/usr/bin/ansible-playbook --inventory=hosts --tags "delete users"
---
- name: Show off some basic Ansible features
  hosts: main 
  remote_user: "{{ ansible_user }}" 
  become_method: sudo 
  become: true
  become_user: root

  roles:
    - common
