---

- hosts: all
  roles:
    - { role: ncrnet.EPEL, tags: [ 'epel' ]}
    - { role: common, tags: [ 'packages', 'testonly' ]}
# dont enable until fixed   - ncrnet.firewalld
    - net.buffers
    - ntpq
# local proxy servers have apache temp fix.
- hosts: local_proxy
  roles:
    - apache
