#!/usr/bin/ansible-playbook --inventory=hosts --tags "delete users"
---
  remote_user: "{{ ansible_user }}" 
  become_method: sudo 
  become: true
  become_user: root

-hosts: [test]

  roles:
    - common
