---
# tasks file for mongodb install
#

- name: Add MongoDB Repository
  yum_repository:
    name: MongoDBRepository
    description: MongoDB.org Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/x86_64/
    gpgkey: https://www.mongodb.org/static/pgp/server-3.4.asc
    gpgcheck: yes

- name: Install MongoDB via yum
  yum: name=mongodb-org state=latest


# Ensure directory for keyfile exists.
- name: Directory for keyfile
  tags:
    - install
  file:
    path: "/opt/mongo_info"
    state: "directory"
    owner: "mongod"
    group: "mongod"

- name: Copy key to mongo_info
  copy: src=MyKey.asc dest=/opt/mongo_info/MyKey.asc mode=0400 




# Ensure MongoDB running
- name: Enabling MongoDB on boot and starting 
  service: 
    name: "mongod" 
    state: started 
    enabled: yes 


